# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assetLibrary_UI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
     = QtCore.QString.fromUtf8
except AttributeError:
    def (s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_sceneManager_MainWindow(object):
    def setupUi(self, sceneManager_MainWindow):
        sceneManager_MainWindow.setObjectName(("sceneManager_MainWindow"))
        sceneManager_MainWindow.resize(866, 565)

        self.centralwidget = QtGui.QWidget(sceneManager_MainWindow)
        self.centralwidget.setObjectName(("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 22))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName(("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_4.setObjectName(("gridLayout_4"))
        self.tabWidget.addTab(self.tab, (""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(("tab_2"))
        self.tabWidget.addTab(self.tab_2, (""))
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.bottom_horizontalLayout = QtGui.QHBoxLayout()
        self.bottom_horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.bottom_horizontalLayout.setSpacing(6)
        self.bottom_horizontalLayout.setObjectName(("bottom_horizontalLayout"))
        self.createNewAsset_pushButton = QtGui.QPushButton(self.centralwidget)
        self.createNewAsset_pushButton.setMinimumSize(QtCore.QSize(150, 45))
        self.createNewAsset_pushButton.setMaximumSize(QtCore.QSize(15000, 45))
        self.createNewAsset_pushButton.setText(("Create New Asset"))
        self.createNewAsset_pushButton.setObjectName(("createNewAsset_pushButton"))
        self.bottom_horizontalLayout.addWidget(self.createNewAsset_pushButton)
        self.bottom_horizontalLayout.setStretch(0, 1)
        self.gridLayout_3.addLayout(self.bottom_horizontalLayout, 3, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(("splitter"))
        self.assets_listWidget = QtGui.QListWidget(self.splitter)
        self.assets_listWidget.setObjectName(("assets_listWidget"))
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(("frame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setContentsMargins(-1, -1, 0, 0)
        self.gridLayout_6.setObjectName(("gridLayout_6"))
        self.rightBelow_verticalLayout = QtGui.QVBoxLayout()
        self.rightBelow_verticalLayout.setObjectName(("rightBelow_verticalLayout"))
        self.assetNotes_label = QtGui.QLabel(self.frame)
        self.assetNotes_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.assetNotes_label.setText(("Asset Notes"))
        self.assetNotes_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.assetNotes_label.setObjectName(("assetNotes_label"))
        self.rightBelow_verticalLayout.addWidget(self.assetNotes_label)
        self.notes_textEdit = QtGui.QTextEdit(self.frame)
        self.notes_textEdit.setObjectName(("notes_textEdit"))
        self.rightBelow_verticalLayout.addWidget(self.notes_textEdit)
        self.thumb_label = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumb_label.sizePolicy().hasHeightForWidth())
        self.thumb_label.setSizePolicy(sizePolicy)
        self.thumb_label.setMinimumSize(QtCore.QSize(221, 124))
        self.thumb_label.setMaximumSize(QtCore.QSize(884, 496))
        self.thumb_label.setSizeIncrement(QtCore.QSize(1, 1))
        self.thumb_label.setBaseSize(QtCore.QSize(0, 0))
        self.thumb_label.setFrameShape(QtGui.QFrame.Box)
        self.thumb_label.setScaledContents(False)
        self.thumb_label.setAlignment(QtCore.Qt.AlignCenter)
        self.thumb_label.setObjectName(("thumb_label"))
        self.rightBelow_verticalLayout.addWidget(self.thumb_label)
        self.gridLayout_6.addLayout(self.rightBelow_verticalLayout, 3, 0, 1, 1)
        self.rightUp_gridLayout = QtGui.QGridLayout()
        self.rightUp_gridLayout.setContentsMargins(-1, -1, 10, 10)
        self.rightUp_gridLayout.setObjectName(("rightUp_gridLayout"))
        self.importOnly_pushButton = QtGui.QPushButton(self.frame)
        self.importOnly_pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.importOnly_pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.importOnly_pushButton.setText(("Import Only"))
        self.importOnly_pushButton.setObjectName(("importOnly_pushButton"))
        self.rightUp_gridLayout.addWidget(self.importOnly_pushButton, 1, 0, 1, 1)
        self.load_pushButton = QtGui.QPushButton(self.frame)
        self.load_pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.load_pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.load_pushButton.setText(("Load"))
        self.load_pushButton.setObjectName(("load_pushButton"))
        self.rightUp_gridLayout.addWidget(self.load_pushButton, 0, 3, 1, 1)
        self.importObj_pushButton = QtGui.QPushButton(self.frame)
        self.importObj_pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.importObj_pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.importObj_pushButton.setText(("Import .obj"))
        self.importObj_pushButton.setObjectName(("importObj_pushButton"))
        self.rightUp_gridLayout.addWidget(self.importObj_pushButton, 1, 3, 1, 1)
        self.importAndCopy_pushButton = QtGui.QPushButton(self.frame)
        self.importAndCopy_pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.importAndCopy_pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.importAndCopy_pushButton.setText(("Import/Copy Textures"))
        self.importAndCopy_pushButton.setObjectName(("importAndCopy_pushButton"))
        self.rightUp_gridLayout.addWidget(self.importAndCopy_pushButton, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.rightUp_gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 2, 0, 1, 1)
        sceneManager_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(sceneManager_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 21))
        self.menubar.setObjectName(("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(("menuTools"))
        sceneManager_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(sceneManager_MainWindow)
        self.statusbar.setObjectName(("statusbar"))
        sceneManager_MainWindow.setStatusBar(self.statusbar)
        self.actionCreate_Project = QtGui.QAction(sceneManager_MainWindow)
        self.actionCreate_Project.setObjectName(("actionCreate_Project"))
        self.actionSave_Version = QtGui.QAction(sceneManager_MainWindow)
        self.actionSave_Version.setObjectName(("actionSave_Version"))
        self.actionSave_Base_Scene = QtGui.QAction(sceneManager_MainWindow)
        self.actionSave_Base_Scene.setObjectName(("actionSave_Base_Scene"))
        self.actionLoad_Reference_Scene = QtGui.QAction(sceneManager_MainWindow)
        self.actionLoad_Reference_Scene.setObjectName(("actionLoad_Reference_Scene"))
        self.actionAdd_Remove_Users = QtGui.QAction(sceneManager_MainWindow)
        self.actionAdd_Remove_Users.setObjectName(("actionAdd_Remove_Users"))
        self.actionPreview_Settings = QtGui.QAction(sceneManager_MainWindow)
        self.actionPreview_Settings.setObjectName(("actionPreview_Settings"))
        self.actionDelete_Selected_Base_Scene = QtGui.QAction(sceneManager_MainWindow)
        self.actionDelete_Selected_Base_Scene.setObjectName(("actionDelete_Selected_Base_Scene"))
        self.actionDelete_Reference_of_Selected_Scene = QtGui.QAction(sceneManager_MainWindow)
        self.actionDelete_Reference_of_Selected_Scene.setObjectName(("actionDelete_Reference_of_Selected_Scene"))
        self.actionProject_Report = QtGui.QAction(sceneManager_MainWindow)
        self.actionProject_Report.setObjectName(("actionProject_Report"))
        self.actionCheck_References = QtGui.QAction(sceneManager_MainWindow)
        self.actionCheck_References.setObjectName(("actionCheck_References"))
        self.actionImage_Manager = QtGui.QAction(sceneManager_MainWindow)
        self.actionImage_Manager.setObjectName(("actionImage_Manager"))
        self.actionSequence_Viewer = QtGui.QAction(sceneManager_MainWindow)
        self.actionSequence_Viewer.setObjectName(("actionSequence_Viewer"))
        self.actionImport_Selected_Item = QtGui.QAction(sceneManager_MainWindow)
        self.actionImport_Selected_Item.setObjectName(("actionImport_Selected_Item"))
        self.actionImport_Only = QtGui.QAction(sceneManager_MainWindow)
        self.actionImport_Only.setObjectName(("actionImport_Only"))
        self.actionAdd_New_Library = QtGui.QAction(sceneManager_MainWindow)
        self.actionAdd_New_Library.setObjectName(("actionAdd_New_Library"))
        self.actionRemove_Library = QtGui.QAction(sceneManager_MainWindow)
        self.actionRemove_Library.setObjectName(("actionRemove_Library"))
        self.menuFile.addAction(self.actionAdd_New_Library)
        self.menuFile.addAction(self.actionCreate_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Reference_Scene)
        self.menuFile.addAction(self.actionImport_Selected_Item)
        self.menuFile.addAction(self.actionImport_Only)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAdd_Remove_Users)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRemove_Library)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(sceneManager_MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(sceneManager_MainWindow)

    def retranslateUi(self, sceneManager_MainWindow):
        sceneManager_MainWindow.setWindowTitle(_translate("sceneManager_MainWindow", "Scene Manager", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("sceneManager_MainWindow", "Tab 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("sceneManager_MainWindow", "Tab 2", None))
        self.thumb_label.setText(_translate("sceneManager_MainWindow", "TextLabel", None))
        self.menuFile.setTitle(_translate("sceneManager_MainWindow", "File", None))
        self.menuTools.setTitle(_translate("sceneManager_MainWindow", "Tools", None))
        self.actionCreate_Project.setText(_translate("sceneManager_MainWindow", "Create New Asset", None))
        self.actionSave_Version.setText(_translate("sceneManager_MainWindow", "Save Version", None))
        self.actionSave_Base_Scene.setText(_translate("sceneManager_MainWindow", "Save Base Scene", None))
        self.actionLoad_Reference_Scene.setText(_translate("sceneManager_MainWindow", "Load Selected Asset", None))
        self.actionAdd_Remove_Users.setText(_translate("sceneManager_MainWindow", "Delete Selected Asset", None))
        self.actionPreview_Settings.setText(_translate("sceneManager_MainWindow", "Preview Settings", None))
        self.actionDelete_Selected_Base_Scene.setText(_translate("sceneManager_MainWindow", "Delete Selected Base Scene", None))
        self.actionDelete_Reference_of_Selected_Scene.setText(_translate("sceneManager_MainWindow", "Delete Reference of Selected Scene", None))
        self.actionProject_Report.setText(_translate("sceneManager_MainWindow", "Project Report", None))
        self.actionCheck_References.setText(_translate("sceneManager_MainWindow", "Check References", None))
        self.actionImage_Manager.setText(_translate("sceneManager_MainWindow", "Image Manager", None))
        self.actionSequence_Viewer.setText(_translate("sceneManager_MainWindow", "Sequence Viewer", None))
        self.actionImport_Selected_Item.setText(_translate("sceneManager_MainWindow", "Import and Copy Textures", None))
        self.actionImport_Only.setText(_translate("sceneManager_MainWindow", "Import Only", None))
        self.actionAdd_New_Library.setText(_translate("sceneManager_MainWindow", "Add New Library", None))
        self.actionRemove_Library.setText(_translate("sceneManager_MainWindow", "Remove Library", None))

