# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assetLibrary_UI_TAB_STR.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
     = QtCore.QString.fromUtf8
except AttributeError:
    def (s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(("Dialog"))
        Dialog.resize(722, 468)
        self.splitter = QtGui.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(20, 10, 693, 437))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(("splitter"))
        self.frame_5 = QtGui.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName(("frame_5"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName(("gridLayout_10"))
        self.rightBelow_verticalLayout_5 = QtGui.QVBoxLayout()
        self.rightBelow_verticalLayout_5.setSpacing(0)
        self.rightBelow_verticalLayout_5.setObjectName(("rightBelow_verticalLayout_5"))
        self.assets_listWidget_4 = QtGui.QListWidget(self.frame_5)
        self.assets_listWidget_4.setToolTip((""))
        self.assets_listWidget_4.setStatusTip((""))
        self.assets_listWidget_4.setWhatsThis((""))
        self.assets_listWidget_4.setAccessibleName((""))
        self.assets_listWidget_4.setAccessibleDescription((""))
        self.assets_listWidget_4.setObjectName(("assets_listWidget_4"))
        self.rightBelow_verticalLayout_5.addWidget(self.assets_listWidget_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(("horizontalLayout_3"))
        self.filter_label_2 = QtGui.QLabel(self.frame_5)
        self.filter_label_2.setObjectName(("filter_label_2"))
        self.horizontalLayout_3.addWidget(self.filter_label_2)
        self.filter_lineEdit_2 = QtGui.QLineEdit(self.frame_5)
        self.filter_lineEdit_2.setObjectName(("filter_lineEdit_2"))
        self.horizontalLayout_3.addWidget(self.filter_lineEdit_2)
        self.rightBelow_verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_10.addLayout(self.rightBelow_verticalLayout_5, 2, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.splitter)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(("frame_6"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_11.setContentsMargins(-1, -1, 0, 0)
        self.gridLayout_11.setObjectName(("gridLayout_11"))
        self.rightBelow_verticalLayout_6 = QtGui.QVBoxLayout()
        self.rightBelow_verticalLayout_6.setObjectName(("rightBelow_verticalLayout_6"))
        self.assetNotes_label_4 = QtGui.QLabel(self.frame_6)
        self.assetNotes_label_4.setToolTip((""))
        self.assetNotes_label_4.setStatusTip((""))
        self.assetNotes_label_4.setWhatsThis((""))
        self.assetNotes_label_4.setAccessibleName((""))
        self.assetNotes_label_4.setAccessibleDescription((""))
        self.assetNotes_label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.assetNotes_label_4.setText(("Asset Notes"))
        self.assetNotes_label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.assetNotes_label_4.setObjectName(("assetNotes_label_4"))
        self.rightBelow_verticalLayout_6.addWidget(self.assetNotes_label_4)
        self.notes_textEdit_4 = QtGui.QTextEdit(self.frame_6)
        self.notes_textEdit_4.setObjectName(("notes_textEdit_4"))
        self.rightBelow_verticalLayout_6.addWidget(self.notes_textEdit_4)
        self.thumb_label_4 = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumb_label_4.sizePolicy().hasHeightForWidth())
        self.thumb_label_4.setSizePolicy(sizePolicy)
        self.thumb_label_4.setMinimumSize(QtCore.QSize(221, 124))
        self.thumb_label_4.setMaximumSize(QtCore.QSize(884, 496))
        self.thumb_label_4.setSizeIncrement(QtCore.QSize(1, 1))
        self.thumb_label_4.setBaseSize(QtCore.QSize(0, 0))
        self.thumb_label_4.setToolTip((""))
        self.thumb_label_4.setStatusTip((""))
        self.thumb_label_4.setWhatsThis((""))
        self.thumb_label_4.setAccessibleName((""))
        self.thumb_label_4.setAccessibleDescription((""))
        self.thumb_label_4.setFrameShape(QtGui.QFrame.Box)
        self.thumb_label_4.setScaledContents(False)
        self.thumb_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.thumb_label_4.setObjectName(("thumb_label_4"))
        self.rightBelow_verticalLayout_6.addWidget(self.thumb_label_4)
        self.gridLayout_11.addLayout(self.rightBelow_verticalLayout_6, 3, 0, 1, 1)
        self.rightUp_gridLayout_4 = QtGui.QGridLayout()
        self.rightUp_gridLayout_4.setContentsMargins(-1, -1, 10, 10)
        self.rightUp_gridLayout_4.setObjectName(("rightUp_gridLayout_4"))
        self.importOnly_pushButton_4 = QtGui.QPushButton(self.frame_6)
        self.importOnly_pushButton_4.setMinimumSize(QtCore.QSize(100, 30))
        self.importOnly_pushButton_4.setMaximumSize(QtCore.QSize(150, 30))
        self.importOnly_pushButton_4.setToolTip((""))
        self.importOnly_pushButton_4.setStatusTip((""))
        self.importOnly_pushButton_4.setWhatsThis((""))
        self.importOnly_pushButton_4.setAccessibleName((""))
        self.importOnly_pushButton_4.setAccessibleDescription((""))
        self.importOnly_pushButton_4.setText(("Import Only"))
        self.importOnly_pushButton_4.setObjectName(("importOnly_pushButton_4"))
        self.rightUp_gridLayout_4.addWidget(self.importOnly_pushButton_4, 1, 0, 1, 1)
        self.load_pushButton_4 = QtGui.QPushButton(self.frame_6)
        self.load_pushButton_4.setMinimumSize(QtCore.QSize(100, 30))
        self.load_pushButton_4.setMaximumSize(QtCore.QSize(150, 30))
        self.load_pushButton_4.setToolTip((""))
        self.load_pushButton_4.setStatusTip((""))
        self.load_pushButton_4.setWhatsThis((""))
        self.load_pushButton_4.setAccessibleName((""))
        self.load_pushButton_4.setAccessibleDescription((""))
        self.load_pushButton_4.setText(("Load"))
        self.load_pushButton_4.setObjectName(("load_pushButton_4"))
        self.rightUp_gridLayout_4.addWidget(self.load_pushButton_4, 0, 3, 1, 1)
        self.importObj_pushButton_4 = QtGui.QPushButton(self.frame_6)
        self.importObj_pushButton_4.setMinimumSize(QtCore.QSize(100, 30))
        self.importObj_pushButton_4.setMaximumSize(QtCore.QSize(150, 30))
        self.importObj_pushButton_4.setToolTip((""))
        self.importObj_pushButton_4.setStatusTip((""))
        self.importObj_pushButton_4.setWhatsThis((""))
        self.importObj_pushButton_4.setAccessibleName((""))
        self.importObj_pushButton_4.setAccessibleDescription((""))
        self.importObj_pushButton_4.setText(("Import .obj"))
        self.importObj_pushButton_4.setObjectName(("importObj_pushButton_4"))
        self.rightUp_gridLayout_4.addWidget(self.importObj_pushButton_4, 1, 3, 1, 1)
        self.importAndCopy_pushButton_4 = QtGui.QPushButton(self.frame_6)
        self.importAndCopy_pushButton_4.setMinimumSize(QtCore.QSize(100, 30))
        self.importAndCopy_pushButton_4.setMaximumSize(QtCore.QSize(150, 30))
        self.importAndCopy_pushButton_4.setToolTip((""))
        self.importAndCopy_pushButton_4.setStatusTip((""))
        self.importAndCopy_pushButton_4.setWhatsThis((""))
        self.importAndCopy_pushButton_4.setAccessibleName((""))
        self.importAndCopy_pushButton_4.setAccessibleDescription((""))
        self.importAndCopy_pushButton_4.setText(("Import/Copy Textures"))
        self.importAndCopy_pushButton_4.setObjectName(("importAndCopy_pushButton_4"))
        self.rightUp_gridLayout_4.addWidget(self.importAndCopy_pushButton_4, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.rightUp_gridLayout_4, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.filter_label_2.setText(_translate("Dialog", "Filter", None))
        self.thumb_label_4.setText(_translate("Dialog", "TextLabel", None))

