# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageViewer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
     = QtCore.QString.fromUtf8
except AttributeError:
    def (s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(("MainWindow"))
        MainWindow.resize(670, 624)
        MainWindow.setToolTip((""))
        MainWindow.setStatusTip((""))
        MainWindow.setWhatsThis((""))
        MainWindow.setAccessibleName((""))
        MainWindow.setAccessibleDescription((""))
        MainWindow.setWindowFilePath((""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(("gridLayout"))
        self.recursive_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.recursive_checkBox.setToolTip((""))
        self.recursive_checkBox.setStatusTip((""))
        self.recursive_checkBox.setWhatsThis((""))
        self.recursive_checkBox.setAccessibleName((""))
        self.recursive_checkBox.setAccessibleDescription((""))
        self.recursive_checkBox.setText(("Recursive"))
        self.recursive_checkBox.setChecked(True)
        self.recursive_checkBox.setObjectName(("recursive_checkBox"))
        self.gridLayout.addWidget(self.recursive_checkBox, 0, 3, 1, 1)
        self.rootFolder_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.rootFolder_lineEdit.setToolTip((""))
        self.rootFolder_lineEdit.setStatusTip((""))
        self.rootFolder_lineEdit.setWhatsThis((""))
        self.rootFolder_lineEdit.setAccessibleName((""))
        self.rootFolder_lineEdit.setAccessibleDescription((""))
        self.rootFolder_lineEdit.setInputMask((""))
        self.rootFolder_lineEdit.setText((""))
        self.rootFolder_lineEdit.setPlaceholderText((""))
        self.rootFolder_lineEdit.setObjectName(("rootFolder_lineEdit"))
        self.gridLayout.addWidget(self.rootFolder_lineEdit, 0, 1, 1, 1)
        self.browse_pushButton = QtGui.QPushButton(self.centralwidget)
        self.browse_pushButton.setToolTip((""))
        self.browse_pushButton.setStatusTip((""))
        self.browse_pushButton.setWhatsThis((""))
        self.browse_pushButton.setAccessibleName((""))
        self.browse_pushButton.setAccessibleDescription((""))
        self.browse_pushButton.setText(("Browse"))
        self.browse_pushButton.setObjectName(("browse_pushButton"))
        self.gridLayout.addWidget(self.browse_pushButton, 0, 2, 1, 1)
        self.rootFolder_label = QtGui.QLabel(self.centralwidget)
        self.rootFolder_label.setToolTip((""))
        self.rootFolder_label.setStatusTip((""))
        self.rootFolder_label.setWhatsThis((""))
        self.rootFolder_label.setAccessibleName((""))
        self.rootFolder_label.setAccessibleDescription((""))
        self.rootFolder_label.setFrameShape(QtGui.QFrame.Box)
        self.rootFolder_label.setLineWidth(1)
        self.rootFolder_label.setText(("Root Folder:"))
        self.rootFolder_label.setTextFormat(QtCore.Qt.AutoText)
        self.rootFolder_label.setScaledContents(False)
        self.rootFolder_label.setObjectName(("rootFolder_label"))
        self.gridLayout.addWidget(self.rootFolder_label, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(("splitter"))
        self.directories_treeWidget = QtGui.QTreeWidget(self.splitter)
        self.directories_treeWidget.setToolTip((""))
        self.directories_treeWidget.setStatusTip((""))
        self.directories_treeWidget.setWhatsThis((""))
        self.directories_treeWidget.setAccessibleName((""))
        self.directories_treeWidget.setAccessibleDescription((""))
        self.directories_treeWidget.setObjectName(("directories_treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.directories_treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.directories_treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.directories_treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.directories_treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.directories_treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.directories_treeWidget)
        self.sequences_listWidget = QtGui.QListWidget(self.splitter)
        self.sequences_listWidget.setToolTip((""))
        self.sequences_listWidget.setStatusTip((""))
        self.sequences_listWidget.setWhatsThis((""))
        self.sequences_listWidget.setAccessibleName((""))
        self.sequences_listWidget.setAccessibleDescription((""))
        self.sequences_listWidget.setObjectName(("sequences_listWidget"))
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 21))
        self.menubar.setObjectName(("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Viewer", None))
        self.directories_treeWidget.headerItem().setText(0, _translate("MainWindow", "Directories", None))
        __sortingEnabled = self.directories_treeWidget.isSortingEnabled()
        self.directories_treeWidget.setSortingEnabled(False)
        self.directories_treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Shot01", None))
        self.directories_treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Diffuse", None))
        self.directories_treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Fresnel", None))
        self.directories_treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Matte", None))
        self.directories_treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Subsurface", None))
        self.directories_treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "Beauty", None))
        self.directories_treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "asdf", None))
        self.directories_treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Shot02", None))
        self.directories_treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Shot03", None))
        self.directories_treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "SubProject01", None))
        self.directories_treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "Shot01", None))
        self.directories_treeWidget.topLevelItem(4).child(0).child(0).setText(0, _translate("MainWindow", "Diffuse", None))
        self.directories_treeWidget.topLevelItem(4).child(0).child(1).setText(0, _translate("MainWindow", "Beauty", None))
        self.directories_treeWidget.topLevelItem(4).child(0).child(2).setText(0, _translate("MainWindow", "Matte", None))
        self.directories_treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "Shot02", None))
        self.directories_treeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "Shot03", None))
        self.directories_treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "SubProject02", None))
        self.directories_treeWidget.setSortingEnabled(__sortingEnabled)

