# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager_mainUI_002.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(680, 600)
        MainWindow.setMaximumSize(QtCore.QSize(680, 600))
        MainWindow.setWindowTitle(_fromUtf8("Scene Manager"))
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setStatusTip(_fromUtf8(""))
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setAccessibleName(_fromUtf8(""))
        MainWindow.setAccessibleDescription(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.projectPath_label = QtGui.QLabel(self.centralwidget)
        self.projectPath_label.setGeometry(QtCore.QRect(30, 30, 51, 21))
        self.projectPath_label.setToolTip(_fromUtf8(""))
        self.projectPath_label.setStatusTip(_fromUtf8(""))
        self.projectPath_label.setWhatsThis(_fromUtf8(""))
        self.projectPath_label.setAccessibleName(_fromUtf8(""))
        self.projectPath_label.setAccessibleDescription(_fromUtf8(""))
        self.projectPath_label.setFrameShape(QtGui.QFrame.Box)
        self.projectPath_label.setLineWidth(1)
        self.projectPath_label.setText(_fromUtf8("Project:"))
        self.projectPath_label.setTextFormat(QtCore.Qt.AutoText)
        self.projectPath_label.setScaledContents(False)
        self.projectPath_label.setObjectName(_fromUtf8("projectPath_label"))
        self.projectPath_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.projectPath_lineEdit.setGeometry(QtCore.QRect(90, 30, 471, 21))
        self.projectPath_lineEdit.setToolTip(_fromUtf8(""))
        self.projectPath_lineEdit.setStatusTip(_fromUtf8(""))
        self.projectPath_lineEdit.setWhatsThis(_fromUtf8(""))
        self.projectPath_lineEdit.setAccessibleName(_fromUtf8(""))
        self.projectPath_lineEdit.setAccessibleDescription(_fromUtf8(""))
        self.projectPath_lineEdit.setObjectName(_fromUtf8("projectPath_lineEdit"))
        self.setProject_pushButton = QtGui.QPushButton(self.centralwidget)
        self.setProject_pushButton.setGeometry(QtCore.QRect(580, 30, 75, 23))
        self.setProject_pushButton.setToolTip(_fromUtf8(""))
        self.setProject_pushButton.setStatusTip(_fromUtf8(""))
        self.setProject_pushButton.setWhatsThis(_fromUtf8(""))
        self.setProject_pushButton.setAccessibleName(_fromUtf8(""))
        self.setProject_pushButton.setAccessibleDescription(_fromUtf8(""))
        self.setProject_pushButton.setText(_fromUtf8("SET"))
        self.setProject_pushButton.setObjectName(_fromUtf8("setProject_pushButton"))
        self.category_tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.category_tabWidget.setGeometry(QtCore.QRect(30, 110, 621, 21))
        self.category_tabWidget.setToolTip(_fromUtf8(""))
        self.category_tabWidget.setStatusTip(_fromUtf8(""))
        self.category_tabWidget.setWhatsThis(_fromUtf8(""))
        self.category_tabWidget.setAccessibleName(_fromUtf8(""))
        self.category_tabWidget.setAccessibleDescription(_fromUtf8(""))
        self.category_tabWidget.setDocumentMode(True)
        self.category_tabWidget.setObjectName(_fromUtf8("category_tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.category_tabWidget.addTab(self.tab, _fromUtf8("Model"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.category_tabWidget.addTab(self.tab_2, _fromUtf8("Shading"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.category_tabWidget.addTab(self.tab_3, _fromUtf8("Rig"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.category_tabWidget.addTab(self.tab_4, _fromUtf8("Animation"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.category_tabWidget.addTab(self.tab_5, _fromUtf8("Render"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.category_tabWidget.addTab(self.tab_6, _fromUtf8("Other"))
        self.loadMode_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.loadMode_radioButton.setGeometry(QtCore.QRect(30, 67, 82, 31))
        self.loadMode_radioButton.setToolTip(_fromUtf8(""))
        self.loadMode_radioButton.setStatusTip(_fromUtf8(""))
        self.loadMode_radioButton.setWhatsThis(_fromUtf8(""))
        self.loadMode_radioButton.setAccessibleName(_fromUtf8(""))
        self.loadMode_radioButton.setAccessibleDescription(_fromUtf8(""))
        self.loadMode_radioButton.setText(_fromUtf8("Load Mode"))
        self.loadMode_radioButton.setChecked(True)
        self.loadMode_radioButton.setObjectName(_fromUtf8("loadMode_radioButton"))
        self.referenceMode_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.referenceMode_radioButton.setGeometry(QtCore.QRect(130, 67, 101, 31))
        self.referenceMode_radioButton.setToolTip(_fromUtf8(""))
        self.referenceMode_radioButton.setStatusTip(_fromUtf8(""))
        self.referenceMode_radioButton.setWhatsThis(_fromUtf8(""))
        self.referenceMode_radioButton.setAccessibleName(_fromUtf8(""))
        self.referenceMode_radioButton.setAccessibleDescription(_fromUtf8(""))
        self.referenceMode_radioButton.setText(_fromUtf8("Reference Mode"))
        self.referenceMode_radioButton.setObjectName(_fromUtf8("referenceMode_radioButton"))
        self.userName_comboBox = QtGui.QComboBox(self.centralwidget)
        self.userName_comboBox.setGeometry(QtCore.QRect(553, 70, 101, 31))
        self.userName_comboBox.setToolTip(_fromUtf8(""))
        self.userName_comboBox.setStatusTip(_fromUtf8(""))
        self.userName_comboBox.setWhatsThis(_fromUtf8(""))
        self.userName_comboBox.setAccessibleName(_fromUtf8(""))
        self.userName_comboBox.setAccessibleDescription(_fromUtf8(""))
        self.userName_comboBox.setObjectName(_fromUtf8("userName_comboBox"))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.setItemText(0, _fromUtf8("Arda Kutlu"))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.setItemText(1, _fromUtf8("Ilhan Yilmaz"))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.setItemText(2, _fromUtf8("Sinan Iren"))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.setItemText(3, _fromUtf8("Cihan Cicekel"))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.setItemText(4, _fromUtf8("Emir Karasakal"))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.setItemText(5, _fromUtf8("Orcun Ozdemir"))
        self.userName_label = QtGui.QLabel(self.centralwidget)
        self.userName_label.setGeometry(QtCore.QRect(520, 70, 31, 31))
        self.userName_label.setToolTip(_fromUtf8(""))
        self.userName_label.setStatusTip(_fromUtf8(""))
        self.userName_label.setWhatsThis(_fromUtf8(""))
        self.userName_label.setAccessibleName(_fromUtf8(""))
        self.userName_label.setAccessibleDescription(_fromUtf8(""))
        self.userName_label.setText(_fromUtf8("User:"))
        self.userName_label.setObjectName(_fromUtf8("userName_label"))
        self.scenes_listWidget = QtGui.QListWidget(self.centralwidget)
        self.scenes_listWidget.setGeometry(QtCore.QRect(30, 140, 381, 351))
        self.scenes_listWidget.setToolTip(_fromUtf8(""))
        self.scenes_listWidget.setStatusTip(_fromUtf8(""))
        self.scenes_listWidget.setWhatsThis(_fromUtf8(""))
        self.scenes_listWidget.setAccessibleName(_fromUtf8(""))
        self.scenes_listWidget.setAccessibleDescription(_fromUtf8(""))
        self.scenes_listWidget.setObjectName(_fromUtf8("scenes_listWidget"))
        self.notes_textEdit = QtGui.QTextEdit(self.centralwidget)
        self.notes_textEdit.setGeometry(QtCore.QRect(430, 260, 221, 231))
        self.notes_textEdit.setToolTip(_fromUtf8(""))
        self.notes_textEdit.setStatusTip(_fromUtf8(""))
        self.notes_textEdit.setWhatsThis(_fromUtf8(""))
        self.notes_textEdit.setAccessibleName(_fromUtf8(""))
        self.notes_textEdit.setAccessibleDescription(_fromUtf8(""))
        self.notes_textEdit.setObjectName(_fromUtf8("notes_textEdit"))
        self.version_comboBox = QtGui.QComboBox(self.centralwidget)
        self.version_comboBox.setGeometry(QtCore.QRect(490, 150, 71, 31))
        self.version_comboBox.setToolTip(_fromUtf8(""))
        self.version_comboBox.setStatusTip(_fromUtf8(""))
        self.version_comboBox.setWhatsThis(_fromUtf8(""))
        self.version_comboBox.setAccessibleName(_fromUtf8(""))
        self.version_comboBox.setAccessibleDescription(_fromUtf8(""))
        self.version_comboBox.setObjectName(_fromUtf8("version_comboBox"))
        self.version_label = QtGui.QLabel(self.centralwidget)
        self.version_label.setGeometry(QtCore.QRect(430, 151, 51, 31))
        self.version_label.setToolTip(_fromUtf8(""))
        self.version_label.setStatusTip(_fromUtf8(""))
        self.version_label.setWhatsThis(_fromUtf8(""))
        self.version_label.setAccessibleName(_fromUtf8(""))
        self.version_label.setAccessibleDescription(_fromUtf8(""))
        self.version_label.setFrameShape(QtGui.QFrame.Box)
        self.version_label.setFrameShadow(QtGui.QFrame.Plain)
        self.version_label.setText(_fromUtf8("Version:"))
        self.version_label.setObjectName(_fromUtf8("version_label"))
        self.makeReference_pushButton = QtGui.QPushButton(self.centralwidget)
        self.makeReference_pushButton.setGeometry(QtCore.QRect(430, 200, 131, 23))
        self.makeReference_pushButton.setToolTip(_fromUtf8("Creates a copy the scene as \'forReference\' file"))
        self.makeReference_pushButton.setStatusTip(_fromUtf8(""))
        self.makeReference_pushButton.setWhatsThis(_fromUtf8(""))
        self.makeReference_pushButton.setAccessibleName(_fromUtf8(""))
        self.makeReference_pushButton.setAccessibleDescription(_fromUtf8(""))
        self.makeReference_pushButton.setText(_fromUtf8("Make Reference"))
        self.makeReference_pushButton.setShortcut(_fromUtf8(""))
        self.makeReference_pushButton.setObjectName(_fromUtf8("makeReference_pushButton"))
        self.notes_label = QtGui.QLabel(self.centralwidget)
        self.notes_label.setGeometry(QtCore.QRect(430, 240, 46, 13))
        self.notes_label.setToolTip(_fromUtf8(""))
        self.notes_label.setStatusTip(_fromUtf8(""))
        self.notes_label.setWhatsThis(_fromUtf8(""))
        self.notes_label.setAccessibleName(_fromUtf8(""))
        self.notes_label.setAccessibleDescription(_fromUtf8(""))
        self.notes_label.setText(_fromUtf8("NOTES"))
        self.notes_label.setObjectName(_fromUtf8("notes_label"))
        self.saveScene_pushButton = QtGui.QPushButton(self.centralwidget)
        self.saveScene_pushButton.setGeometry(QtCore.QRect(40, 510, 151, 41))
        self.saveScene_pushButton.setToolTip(_fromUtf8("Saves the Base Scene. This will save the scene and will make versioning possible."))
        self.saveScene_pushButton.setStatusTip(_fromUtf8(""))
        self.saveScene_pushButton.setWhatsThis(_fromUtf8(""))
        self.saveScene_pushButton.setAccessibleName(_fromUtf8(""))
        self.saveScene_pushButton.setAccessibleDescription(_fromUtf8(""))
        self.saveScene_pushButton.setText(_fromUtf8("Save Base Scene"))
        self.saveScene_pushButton.setObjectName(_fromUtf8("saveScene_pushButton"))
        self.saveAsVersion_pushButton = QtGui.QPushButton(self.centralwidget)
        self.saveAsVersion_pushButton.setGeometry(QtCore.QRect(210, 510, 151, 41))
        self.saveAsVersion_pushButton.setToolTip(_fromUtf8("Saves the current scene as a version. A base scene must be present."))
        self.saveAsVersion_pushButton.setStatusTip(_fromUtf8(""))
        self.saveAsVersion_pushButton.setWhatsThis(_fromUtf8(""))
        self.saveAsVersion_pushButton.setAccessibleName(_fromUtf8(""))
        self.saveAsVersion_pushButton.setAccessibleDescription(_fromUtf8(""))
        self.saveAsVersion_pushButton.setText(_fromUtf8("Save As Version"))
        self.saveAsVersion_pushButton.setObjectName(_fromUtf8("saveAsVersion_pushButton"))
        self.load_pushButton = QtGui.QPushButton(self.centralwidget)
        self.load_pushButton.setGeometry(QtCore.QRect(500, 510, 151, 41))
        self.load_pushButton.setToolTip(_fromUtf8("Loads the scene or Creates the selected reference depending on the mode"))
        self.load_pushButton.setStatusTip(_fromUtf8(""))
        self.load_pushButton.setWhatsThis(_fromUtf8(""))
        self.load_pushButton.setAccessibleName(_fromUtf8(""))
        self.load_pushButton.setAccessibleDescription(_fromUtf8(""))
        self.load_pushButton.setText(_fromUtf8("Load / Reference"))
        self.load_pushButton.setObjectName(_fromUtf8("load_pushButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.category_tabWidget.setCurrentIndex(5)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.version_label.setEnabled)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.version_comboBox.setEnabled)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.makeReference_pushButton.setEnabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.version_label.setDisabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.version_comboBox.setDisabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.makeReference_pushButton.setDisabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.notes_textEdit.setDisabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.notes_label.setDisabled)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.notes_textEdit.setEnabled)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.notes_label.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

