# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager_mainUI_001.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(680, 600)
        MainWindow.setMaximumSize(QtCore.QSize(680, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.projectPath_label = QtGui.QLabel(self.centralwidget)
        self.projectPath_label.setGeometry(QtCore.QRect(30, 30, 51, 21))
        self.projectPath_label.setFrameShape(QtGui.QFrame.Box)
        self.projectPath_label.setLineWidth(1)
        self.projectPath_label.setScaledContents(False)
        self.projectPath_label.setObjectName(_fromUtf8("projectPath_label"))
        self.projectPath_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.projectPath_lineEdit.setGeometry(QtCore.QRect(90, 30, 471, 21))
        self.projectPath_lineEdit.setObjectName(_fromUtf8("projectPath_lineEdit"))
        self.setProject_pushButton = QtGui.QPushButton(self.centralwidget)
        self.setProject_pushButton.setGeometry(QtCore.QRect(580, 30, 75, 23))
        self.setProject_pushButton.setObjectName(_fromUtf8("setProject_pushButton"))
        self.category_tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.category_tabWidget.setGeometry(QtCore.QRect(30, 110, 621, 21))
        self.category_tabWidget.setDocumentMode(True)
        self.category_tabWidget.setObjectName(_fromUtf8("category_tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.category_tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.category_tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.category_tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.category_tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.category_tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.category_tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.loadMode_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.loadMode_radioButton.setGeometry(QtCore.QRect(30, 67, 82, 31))
        self.loadMode_radioButton.setChecked(True)
        self.loadMode_radioButton.setObjectName(_fromUtf8("loadMode_radioButton"))
        self.referenceMode_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.referenceMode_radioButton.setGeometry(QtCore.QRect(130, 67, 101, 31))
        self.referenceMode_radioButton.setObjectName(_fromUtf8("referenceMode_radioButton"))
        self.userName_comboBox = QtGui.QComboBox(self.centralwidget)
        self.userName_comboBox.setGeometry(QtCore.QRect(553, 70, 101, 31))
        self.userName_comboBox.setObjectName(_fromUtf8("userName_comboBox"))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_comboBox.addItem(_fromUtf8(""))
        self.userName_label = QtGui.QLabel(self.centralwidget)
        self.userName_label.setGeometry(QtCore.QRect(520, 70, 31, 31))
        self.userName_label.setObjectName(_fromUtf8("userName_label"))
        self.scenes_listWidget = QtGui.QListWidget(self.centralwidget)
        self.scenes_listWidget.setGeometry(QtCore.QRect(30, 140, 381, 351))
        self.scenes_listWidget.setObjectName(_fromUtf8("scenes_listWidget"))
        self.notes_textEdit = QtGui.QTextEdit(self.centralwidget)
        self.notes_textEdit.setGeometry(QtCore.QRect(430, 260, 221, 231))
        self.notes_textEdit.setObjectName(_fromUtf8("notes_textEdit"))
        self.version_comboBox = QtGui.QComboBox(self.centralwidget)
        self.version_comboBox.setGeometry(QtCore.QRect(490, 150, 71, 31))
        self.version_comboBox.setObjectName(_fromUtf8("version_comboBox"))
        self.version_label = QtGui.QLabel(self.centralwidget)
        self.version_label.setGeometry(QtCore.QRect(430, 151, 51, 31))
        self.version_label.setFrameShape(QtGui.QFrame.Box)
        self.version_label.setFrameShadow(QtGui.QFrame.Plain)
        self.version_label.setObjectName(_fromUtf8("version_label"))
        self.makeReference_pushButton = QtGui.QPushButton(self.centralwidget)
        self.makeReference_pushButton.setGeometry(QtCore.QRect(430, 200, 131, 23))
        self.makeReference_pushButton.setShortcut(_fromUtf8(""))
        self.makeReference_pushButton.setObjectName(_fromUtf8("makeReference_pushButton"))
        self.notes_label = QtGui.QLabel(self.centralwidget)
        self.notes_label.setGeometry(QtCore.QRect(430, 240, 46, 13))
        self.notes_label.setObjectName(_fromUtf8("notes_label"))
        self.saveScene_pushButton = QtGui.QPushButton(self.centralwidget)
        self.saveScene_pushButton.setGeometry(QtCore.QRect(40, 510, 151, 41))
        self.saveScene_pushButton.setObjectName(_fromUtf8("saveScene_pushButton"))
        self.saveAsVersion_pushButton = QtGui.QPushButton(self.centralwidget)
        self.saveAsVersion_pushButton.setGeometry(QtCore.QRect(210, 510, 151, 41))
        self.saveAsVersion_pushButton.setObjectName(_fromUtf8("saveAsVersion_pushButton"))
        self.load_pushButton = QtGui.QPushButton(self.centralwidget)
        self.load_pushButton.setGeometry(QtCore.QRect(500, 510, 151, 41))
        self.load_pushButton.setObjectName(_fromUtf8("load_pushButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.category_tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.version_label.setEnabled)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.version_comboBox.setEnabled)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.makeReference_pushButton.setEnabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.version_label.setDisabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.version_comboBox.setDisabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.makeReference_pushButton.setDisabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.notes_textEdit.setDisabled)
        QtCore.QObject.connect(self.referenceMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.notes_label.setDisabled)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.notes_textEdit.setEnabled)
        QtCore.QObject.connect(self.loadMode_radioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.notes_label.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.projectPath_label.setText(_translate("MainWindow", "Project:", None))
        self.setProject_pushButton.setText(_translate("MainWindow", "SET", None))
        self.category_tabWidget.setTabText(self.category_tabWidget.indexOf(self.tab), _translate("MainWindow", "Model", None))
        self.category_tabWidget.setTabText(self.category_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Shading", None))
        self.category_tabWidget.setTabText(self.category_tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Rig", None))
        self.category_tabWidget.setTabText(self.category_tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Animation", None))
        self.category_tabWidget.setTabText(self.category_tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Render", None))
        self.category_tabWidget.setTabText(self.category_tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Other", None))
        self.loadMode_radioButton.setText(_translate("MainWindow", "Load Mode", None))
        self.referenceMode_radioButton.setText(_translate("MainWindow", "Reference Mode", None))
        self.userName_comboBox.setItemText(0, _translate("MainWindow", "Arda Kutlu", None))
        self.userName_comboBox.setItemText(1, _translate("MainWindow", "Ilhan Yilmaz", None))
        self.userName_comboBox.setItemText(2, _translate("MainWindow", "Sinan Iren", None))
        self.userName_comboBox.setItemText(3, _translate("MainWindow", "Cihan Cicekel", None))
        self.userName_comboBox.setItemText(4, _translate("MainWindow", "Emir Karasakal", None))
        self.userName_comboBox.setItemText(5, _translate("MainWindow", "Orcun Ozdemir", None))
        self.userName_label.setText(_translate("MainWindow", "User:", None))
        self.version_label.setText(_translate("MainWindow", "Version:", None))
        self.makeReference_pushButton.setToolTip(_translate("MainWindow", "Creates a copy the scene as \'forReference\' file", None))
        self.makeReference_pushButton.setText(_translate("MainWindow", "Make Reference", None))
        self.notes_label.setText(_translate("MainWindow", "NOTES", None))
        self.saveScene_pushButton.setToolTip(_translate("MainWindow", "Saves the Base Scene. This will save the scene and will make versioning possible.", None))
        self.saveScene_pushButton.setText(_translate("MainWindow", "Save Base Scene", None))
        self.saveAsVersion_pushButton.setToolTip(_translate("MainWindow", "Saves the current scene as a version. A base scene must be present.", None))
        self.saveAsVersion_pushButton.setText(_translate("MainWindow", "Save As Version", None))
        self.load_pushButton.setToolTip(_translate("MainWindow", "Loads the scene or Creates the selected reference depending on the mode", None))
        self.load_pushButton.setText(_translate("MainWindow", "Load / Reference", None))

