# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pbSettings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Playblast_Dialog(object):
    def setupUi(self, Playblast_Dialog):
        Playblast_Dialog.setObjectName(_fromUtf8("Playblast_Dialog"))
        Playblast_Dialog.resize(380, 483)
        Playblast_Dialog.setToolTip(_fromUtf8(""))
        Playblast_Dialog.setStatusTip(_fromUtf8(""))
        Playblast_Dialog.setWhatsThis(_fromUtf8(""))
        Playblast_Dialog.setAccessibleName(_fromUtf8(""))
        Playblast_Dialog.setAccessibleDescription(_fromUtf8(""))
        self.buttonBox = QtGui.QDialogButtonBox(Playblast_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 440, 341, 30))
        self.buttonBox.setToolTip(_fromUtf8(""))
        self.buttonBox.setStatusTip(_fromUtf8(""))
        self.buttonBox.setWhatsThis(_fromUtf8(""))
        self.buttonBox.setAccessibleName(_fromUtf8(""))
        self.buttonBox.setAccessibleDescription(_fromUtf8(""))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.videoproperties_groupBox = QtGui.QGroupBox(Playblast_Dialog)
        self.videoproperties_groupBox.setGeometry(QtCore.QRect(10, 20, 361, 191))
        self.videoproperties_groupBox.setToolTip(_fromUtf8(""))
        self.videoproperties_groupBox.setStatusTip(_fromUtf8(""))
        self.videoproperties_groupBox.setWhatsThis(_fromUtf8(""))
        self.videoproperties_groupBox.setAccessibleName(_fromUtf8(""))
        self.videoproperties_groupBox.setAccessibleDescription(_fromUtf8(""))
        self.videoproperties_groupBox.setTitle(_fromUtf8("Video Properties"))
        self.videoproperties_groupBox.setObjectName(_fromUtf8("videoproperties_groupBox"))
        self.resolutiony_spinBox = QtGui.QSpinBox(self.videoproperties_groupBox)
        self.resolutiony_spinBox.setGeometry(QtCore.QRect(170, 150, 61, 21))
        self.resolutiony_spinBox.setToolTip(_fromUtf8(""))
        self.resolutiony_spinBox.setStatusTip(_fromUtf8(""))
        self.resolutiony_spinBox.setWhatsThis(_fromUtf8(""))
        self.resolutiony_spinBox.setAccessibleName(_fromUtf8(""))
        self.resolutiony_spinBox.setAccessibleDescription(_fromUtf8(""))
        self.resolutiony_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.resolutiony_spinBox.setMinimum(1)
        self.resolutiony_spinBox.setMaximum(4096)
        self.resolutiony_spinBox.setProperty("value", 720)
        self.resolutiony_spinBox.setObjectName(_fromUtf8("resolutiony_spinBox"))
        self.codec_label = QtGui.QLabel(self.videoproperties_groupBox)
        self.codec_label.setGeometry(QtCore.QRect(30, 70, 61, 20))
        self.codec_label.setToolTip(_fromUtf8(""))
        self.codec_label.setStatusTip(_fromUtf8(""))
        self.codec_label.setWhatsThis(_fromUtf8(""))
        self.codec_label.setAccessibleName(_fromUtf8(""))
        self.codec_label.setAccessibleDescription(_fromUtf8(""))
        self.codec_label.setFrameShape(QtGui.QFrame.NoFrame)
        self.codec_label.setFrameShadow(QtGui.QFrame.Plain)
        self.codec_label.setText(_fromUtf8("Codec"))
        self.codec_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.codec_label.setObjectName(_fromUtf8("codec_label"))
        self.quality_label = QtGui.QLabel(self.videoproperties_groupBox)
        self.quality_label.setGeometry(QtCore.QRect(30, 110, 61, 20))
        self.quality_label.setToolTip(_fromUtf8(""))
        self.quality_label.setStatusTip(_fromUtf8(""))
        self.quality_label.setWhatsThis(_fromUtf8(""))
        self.quality_label.setAccessibleName(_fromUtf8(""))
        self.quality_label.setAccessibleDescription(_fromUtf8(""))
        self.quality_label.setFrameShape(QtGui.QFrame.NoFrame)
        self.quality_label.setFrameShadow(QtGui.QFrame.Plain)
        self.quality_label.setText(_fromUtf8("Quality"))
        self.quality_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.quality_label.setObjectName(_fromUtf8("quality_label"))
        self.fileformat_comboBox = QtGui.QComboBox(self.videoproperties_groupBox)
        self.fileformat_comboBox.setGeometry(QtCore.QRect(100, 30, 111, 22))
        self.fileformat_comboBox.setToolTip(_fromUtf8(""))
        self.fileformat_comboBox.setStatusTip(_fromUtf8(""))
        self.fileformat_comboBox.setWhatsThis(_fromUtf8(""))
        self.fileformat_comboBox.setAccessibleName(_fromUtf8(""))
        self.fileformat_comboBox.setAccessibleDescription(_fromUtf8(""))
        self.fileformat_comboBox.setObjectName(_fromUtf8("fileformat_comboBox"))
        self.codec_comboBox = QtGui.QComboBox(self.videoproperties_groupBox)
        self.codec_comboBox.setGeometry(QtCore.QRect(100, 70, 111, 22))
        self.codec_comboBox.setToolTip(_fromUtf8(""))
        self.codec_comboBox.setStatusTip(_fromUtf8(""))
        self.codec_comboBox.setWhatsThis(_fromUtf8(""))
        self.codec_comboBox.setAccessibleName(_fromUtf8(""))
        self.codec_comboBox.setAccessibleDescription(_fromUtf8(""))
        self.codec_comboBox.setObjectName(_fromUtf8("codec_comboBox"))
        self.quality_spinBox = QtGui.QSpinBox(self.videoproperties_groupBox)
        self.quality_spinBox.setGeometry(QtCore.QRect(100, 110, 41, 21))
        self.quality_spinBox.setToolTip(_fromUtf8(""))
        self.quality_spinBox.setStatusTip(_fromUtf8(""))
        self.quality_spinBox.setWhatsThis(_fromUtf8(""))
        self.quality_spinBox.setAccessibleName(_fromUtf8(""))
        self.quality_spinBox.setAccessibleDescription(_fromUtf8(""))
        self.quality_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.quality_spinBox.setMinimum(1)
        self.quality_spinBox.setMaximum(100)
        self.quality_spinBox.setProperty("value", 100)
        self.quality_spinBox.setObjectName(_fromUtf8("quality_spinBox"))
        self.resolution_label = QtGui.QLabel(self.videoproperties_groupBox)
        self.resolution_label.setGeometry(QtCore.QRect(30, 150, 61, 20))
        self.resolution_label.setToolTip(_fromUtf8(""))
        self.resolution_label.setStatusTip(_fromUtf8(""))
        self.resolution_label.setWhatsThis(_fromUtf8(""))
        self.resolution_label.setAccessibleName(_fromUtf8(""))
        self.resolution_label.setAccessibleDescription(_fromUtf8(""))
        self.resolution_label.setFrameShape(QtGui.QFrame.NoFrame)
        self.resolution_label.setFrameShadow(QtGui.QFrame.Plain)
        self.resolution_label.setText(_fromUtf8("Resolution"))
        self.resolution_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resolution_label.setObjectName(_fromUtf8("resolution_label"))
        self.quality_horizontalSlider = QtGui.QSlider(self.videoproperties_groupBox)
        self.quality_horizontalSlider.setGeometry(QtCore.QRect(150, 110, 191, 21))
        self.quality_horizontalSlider.setToolTip(_fromUtf8(""))
        self.quality_horizontalSlider.setStatusTip(_fromUtf8(""))
        self.quality_horizontalSlider.setWhatsThis(_fromUtf8(""))
        self.quality_horizontalSlider.setAccessibleName(_fromUtf8(""))
        self.quality_horizontalSlider.setAccessibleDescription(_fromUtf8(""))
        self.quality_horizontalSlider.setMinimum(1)
        self.quality_horizontalSlider.setMaximum(100)
        self.quality_horizontalSlider.setProperty("value", 100)
        self.quality_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.quality_horizontalSlider.setTickInterval(0)
        self.quality_horizontalSlider.setObjectName(_fromUtf8("quality_horizontalSlider"))
        self.resolutionx_spinBox = QtGui.QSpinBox(self.videoproperties_groupBox)
        self.resolutionx_spinBox.setGeometry(QtCore.QRect(100, 150, 61, 21))
        self.resolutionx_spinBox.setToolTip(_fromUtf8(""))
        self.resolutionx_spinBox.setStatusTip(_fromUtf8(""))
        self.resolutionx_spinBox.setWhatsThis(_fromUtf8(""))
        self.resolutionx_spinBox.setAccessibleName(_fromUtf8(""))
        self.resolutionx_spinBox.setAccessibleDescription(_fromUtf8(""))
        self.resolutionx_spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.resolutionx_spinBox.setMinimum(0)
        self.resolutionx_spinBox.setMaximum(4096)
        self.resolutionx_spinBox.setProperty("value", 1280)
        self.resolutionx_spinBox.setObjectName(_fromUtf8("resolutionx_spinBox"))
        self.fileformat_label = QtGui.QLabel(self.videoproperties_groupBox)
        self.fileformat_label.setGeometry(QtCore.QRect(20, 30, 71, 20))
        self.fileformat_label.setToolTip(_fromUtf8(""))
        self.fileformat_label.setStatusTip(_fromUtf8(""))
        self.fileformat_label.setWhatsThis(_fromUtf8(""))
        self.fileformat_label.setAccessibleName(_fromUtf8(""))
        self.fileformat_label.setAccessibleDescription(_fromUtf8(""))
        self.fileformat_label.setFrameShape(QtGui.QFrame.NoFrame)
        self.fileformat_label.setFrameShadow(QtGui.QFrame.Plain)
        self.fileformat_label.setText(_fromUtf8("Format"))
        self.fileformat_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fileformat_label.setObjectName(_fromUtf8("fileformat_label"))
        self.viewportoptions_groupBox = QtGui.QGroupBox(Playblast_Dialog)
        self.viewportoptions_groupBox.setGeometry(QtCore.QRect(10, 230, 361, 91))
        self.viewportoptions_groupBox.setTitle(_fromUtf8("Viewport Options"))
        self.viewportoptions_groupBox.setObjectName(_fromUtf8("viewportoptions_groupBox"))
        self.polygononly_checkBox = QtGui.QCheckBox(self.viewportoptions_groupBox)
        self.polygononly_checkBox.setGeometry(QtCore.QRect(60, 30, 91, 20))
        self.polygononly_checkBox.setToolTip(_fromUtf8(""))
        self.polygononly_checkBox.setStatusTip(_fromUtf8(""))
        self.polygononly_checkBox.setWhatsThis(_fromUtf8(""))
        self.polygononly_checkBox.setAccessibleName(_fromUtf8(""))
        self.polygononly_checkBox.setAccessibleDescription(_fromUtf8(""))
        self.polygononly_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.polygononly_checkBox.setText(_fromUtf8("Polygon Only"))
        self.polygononly_checkBox.setChecked(True)
        self.polygononly_checkBox.setObjectName(_fromUtf8("polygononly_checkBox"))
        self.showgrid_checkBox = QtGui.QCheckBox(self.viewportoptions_groupBox)
        self.showgrid_checkBox.setGeometry(QtCore.QRect(210, 30, 91, 20))
        self.showgrid_checkBox.setToolTip(_fromUtf8(""))
        self.showgrid_checkBox.setStatusTip(_fromUtf8(""))
        self.showgrid_checkBox.setWhatsThis(_fromUtf8(""))
        self.showgrid_checkBox.setAccessibleName(_fromUtf8(""))
        self.showgrid_checkBox.setAccessibleDescription(_fromUtf8(""))
        self.showgrid_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showgrid_checkBox.setText(_fromUtf8("Show Grid"))
        self.showgrid_checkBox.setChecked(False)
        self.showgrid_checkBox.setObjectName(_fromUtf8("showgrid_checkBox"))
        self.clearselection_checkBox = QtGui.QCheckBox(self.viewportoptions_groupBox)
        self.clearselection_checkBox.setGeometry(QtCore.QRect(60, 60, 91, 20))
        self.clearselection_checkBox.setToolTip(_fromUtf8(""))
        self.clearselection_checkBox.setStatusTip(_fromUtf8(""))
        self.clearselection_checkBox.setWhatsThis(_fromUtf8(""))
        self.clearselection_checkBox.setAccessibleName(_fromUtf8(""))
        self.clearselection_checkBox.setAccessibleDescription(_fromUtf8(""))
        self.clearselection_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.clearselection_checkBox.setText(_fromUtf8("Clear Selection"))
        self.clearselection_checkBox.setChecked(True)
        self.clearselection_checkBox.setObjectName(_fromUtf8("clearselection_checkBox"))
        self.displaytextures_checkBox = QtGui.QCheckBox(self.viewportoptions_groupBox)
        self.displaytextures_checkBox.setGeometry(QtCore.QRect(190, 60, 111, 20))
        self.displaytextures_checkBox.setToolTip(_fromUtf8(""))
        self.displaytextures_checkBox.setStatusTip(_fromUtf8(""))
        self.displaytextures_checkBox.setWhatsThis(_fromUtf8(""))
        self.displaytextures_checkBox.setAccessibleName(_fromUtf8(""))
        self.displaytextures_checkBox.setAccessibleDescription(_fromUtf8(""))
        self.displaytextures_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.displaytextures_checkBox.setText(_fromUtf8("Display Textures"))
        self.displaytextures_checkBox.setChecked(True)
        self.displaytextures_checkBox.setObjectName(_fromUtf8("displaytextures_checkBox"))
        self.hudoptions_groupBox = QtGui.QGroupBox(Playblast_Dialog)
        self.hudoptions_groupBox.setGeometry(QtCore.QRect(10, 340, 361, 81))
        self.hudoptions_groupBox.setToolTip(_fromUtf8(""))
        self.hudoptions_groupBox.setStatusTip(_fromUtf8(""))
        self.hudoptions_groupBox.setWhatsThis(_fromUtf8(""))
        self.hudoptions_groupBox.setAccessibleName(_fromUtf8(""))
        self.hudoptions_groupBox.setAccessibleDescription(_fromUtf8(""))
        self.hudoptions_groupBox.setTitle(_fromUtf8("HUD Options"))
        self.hudoptions_groupBox.setObjectName(_fromUtf8("hudoptions_groupBox"))
        self.showframenumber_checkBox = QtGui.QCheckBox(self.hudoptions_groupBox)
        self.showframenumber_checkBox.setGeometry(QtCore.QRect(20, 20, 131, 20))
        self.showframenumber_checkBox.setToolTip(_fromUtf8(""))
        self.showframenumber_checkBox.setStatusTip(_fromUtf8(""))
        self.showframenumber_checkBox.setWhatsThis(_fromUtf8(""))
        self.showframenumber_checkBox.setAccessibleName(_fromUtf8(""))
        self.showframenumber_checkBox.setAccessibleDescription(_fromUtf8(""))
        self.showframenumber_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showframenumber_checkBox.setText(_fromUtf8("Show Frame Number"))
        self.showframenumber_checkBox.setChecked(True)
        self.showframenumber_checkBox.setObjectName(_fromUtf8("showframenumber_checkBox"))
        self.showscenename_checkBox = QtGui.QCheckBox(self.hudoptions_groupBox)
        self.showscenename_checkBox.setGeometry(QtCore.QRect(20, 50, 131, 20))
        self.showscenename_checkBox.setToolTip(_fromUtf8(""))
        self.showscenename_checkBox.setStatusTip(_fromUtf8(""))
        self.showscenename_checkBox.setWhatsThis(_fromUtf8(""))
        self.showscenename_checkBox.setAccessibleName(_fromUtf8(""))
        self.showscenename_checkBox.setAccessibleDescription(_fromUtf8(""))
        self.showscenename_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showscenename_checkBox.setText(_fromUtf8("Show Scene Name"))
        self.showscenename_checkBox.setChecked(True)
        self.showscenename_checkBox.setObjectName(_fromUtf8("showscenename_checkBox"))
        self.showcategory_checkBox = QtGui.QCheckBox(self.hudoptions_groupBox)
        self.showcategory_checkBox.setGeometry(QtCore.QRect(200, 20, 101, 20))
        self.showcategory_checkBox.setToolTip(_fromUtf8(""))
        self.showcategory_checkBox.setStatusTip(_fromUtf8(""))
        self.showcategory_checkBox.setWhatsThis(_fromUtf8(""))
        self.showcategory_checkBox.setAccessibleName(_fromUtf8(""))
        self.showcategory_checkBox.setAccessibleDescription(_fromUtf8(""))
        self.showcategory_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showcategory_checkBox.setText(_fromUtf8("Show Category"))
        self.showcategory_checkBox.setChecked(False)
        self.showcategory_checkBox.setObjectName(_fromUtf8("showcategory_checkBox"))
        self.showfps_checkBox = QtGui.QCheckBox(self.hudoptions_groupBox)
        self.showfps_checkBox.setGeometry(QtCore.QRect(200, 50, 101, 20))
        self.showfps_checkBox.setToolTip(_fromUtf8(""))
        self.showfps_checkBox.setStatusTip(_fromUtf8(""))
        self.showfps_checkBox.setWhatsThis(_fromUtf8(""))
        self.showfps_checkBox.setAccessibleName(_fromUtf8(""))
        self.showfps_checkBox.setAccessibleDescription(_fromUtf8(""))
        self.showfps_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showfps_checkBox.setText(_fromUtf8("Show FPS"))
        self.showfps_checkBox.setChecked(True)
        self.showfps_checkBox.setObjectName(_fromUtf8("showfps_checkBox"))

        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Playblast_Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Playblast_Dialog.reject)
        QtCore.QObject.connect(self.quality_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.quality_horizontalSlider.setValue)
        QtCore.QObject.connect(self.quality_horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.quality_spinBox.setValue)
        QtCore.QMetaObject.connectSlotsByName(Playblast_Dialog)



